### ISSUE TITLE
집에 가기 전에...

### ISSUE THREAD

**Issue by ks1101** [NESAP-STL/nesap-stl#16]
집에 가기 전에...

1.load_state_dict 관련
로컬(파이참)에서 돌리고 있던 코드가 멈춘 김에 원래 코드에 있던 load_checkpoint를 실험해봤습니다.
resume을 true로 하고 돌리니까 멈춘 부분부터 도네요.
한 김에 디버그모드로 찾아보니까 base.py에 load_state_dict 함수가 basic.py에 있는 load_state_dict으로 연결되더라고요.
![캡처](https://user-images.githubusercontent.com/55044759/127462907-6b304e0a-ff7b-4d7f-9a20-cff36f7d9e4c.JPG)

작성하신 코드가 왜 안 되는지는 모르겠지만 확인해보시면 어떨까 싶어서요.
그리고 원래 코드에서는 model.eval() 없어도 잘 돌아가네요.

2. 결과 관련
031.pth를 실행하려는 이유가 결과를 보기 위해서라고 하셨는데, 
지금 코드에서 그냥 실행하면 summary=trainer.train이 그냥 끝나고 바로 결과를 출력할 것 같은데 어떤가요?
logging.info('Train samples %g time %g s rate %g samples/s', n_train_samples, train_time, n_train_samples / train_time)
바로 이런거 출력할 것 같아요.
그래서 결과를 보려면 결과용 코드를 만들어야하지 않을까 싶습니다.

결과용 코드를 만든다면 valid data에서 임의로 데이터를 뽑아서 평가하는 내용이 되려나요.
전체 데이터에서 앞에 10256개는 train loader에 있으니까 뒤에 4133개 중에서 랜덤으로 54개월 치 데이터를 가져오는 방식으로? 
(validation set은 학습을 시키지 않는다는 전제, 생각을 가지고 한 생각입니다. 이게 틀렸으면 무시해주세요) 
평가용 데이터를 valid data에서 가져오는 게 아니라 input, output 데이터가 따로 있는 편이 더 좋겠지만 없다고 하셨던 것 같네요.

근데 36개월 데이터로 18개월을 예측해야 하는 걸로 알고 있는데

지금 학습 방식은 0-14까지 15개월의 데이터로 1-15까지 15개월의 데이터를 예측하기 때문에 18개월 데이터를 예측하려면 약간의 수정 혹은 추가가 필요하지 않을까 싶습니다.
predrnn_pp.py/forward에서 for문을 수정해서 36-53개월의 학습에서는 x, 입력이 없게 하고 clstm을 돌리거나 
아니면 36-53까지는 입력데이터를 0으로 설정하는건 어떨까요?
(후자는 입력이 0이면, x가 영행렬이면 학습에 영향을 안 주지 않을까 하는 생각에서 나온 아이디어입니다. 아니라면 역시 무시해주세요)
(전자는 CausalLSTMStack.py에서 x가 없게 수정을 해야할 것 같기도 합니다.)
(many-to-many 모델에서 input이나 output이 없는 경우를 보긴 했는데 구현을 어떻게 해야하는지는 모르겠습니다.)

3. 시각화는... 다음기회에
다음이 언젠지는 며느리도 모릅니다.

**Comment by songhune** [comment]
ㅇㅇ 오늘 잠깐 사전미팅 미국쪽이랑 할때 요 이야기도 덧붙여서 만져야 될 부분, 모르는 부분들 몇가지 정리를 좀 해볼려고 합니다. zoom으로 기록해서 구글 드라이브에 올릴테니 확인 부탁드려요.
>04시 35분 업데이트, 이 코드 원작자는 아니지만 코드 중간 컨트리뷰팅을 한 Ray라는 박사분과 미팅을 별도로 잡았습니다. 늦어도 다음주? 정도에 다시한번 미팅을 할 거 같으니, 그때까지 모르는 내용들, 그리고 진행되기 위해서 필요한 것들을 좀 쥐어짜는 식으로 가야 될 필요성은 있어보이네요. 이슈로 올린거 절반 정도는 close해도 될 정도로 줄어들었지만, 그 부분 포함해서 sea데이터의 근본적인 해결책 따위를 물어보는 식으로 진행해 보려고 합니다.

**Comment by songhune** [comment]
코드가 바뀌었는데, 추가적으로 파라미터 --eval 붙이고 돌려보세요, 현재(08.13 nipa서버에서 도는 중) 
![image](https://user-images.githubusercontent.com/14012968/129257978-dbd29645-3f15-4543-a283-4c7bd61c1432.png)
