### ISSUE TITLE
시각화

### ISSUE THREAD

**Issue by ks1101** [NESAP-STL/nesap-stl#18]
sea 데이터에 대해서 시각화를 해봤습니다.

notebooks/ClimateDev.ipynb에서 보여준 방식으로 1장면의 사진을 보여주는 방식이랑
![sea_capture](https://user-images.githubusercontent.com/55044759/130032508-5d535e95-7c5c-46e6-b16e-e040605c64b4.JPG)

여러 달의 데이터를 gif로 만드는 두 가지 방법으로 해봤습니다. (처음 100만큼 자른 데이터입니다.)
![sample](https://user-images.githubusercontent.com/55044759/130032562-a89b3b28-c645-4b62-bff1-1f04dd489ce5.gif)

시각화 방법이 틀렸거나 파일에 문제가 있으면 말씀해주세요.

이 방향이 맞다는 전제 하에 알고 싶은 사항이 세 가지가 있는데요.
1. 시각화한 사진을 보시면 아시겠지만 지도가 세계 지도가 아니라 대서양 위주로 나와있는 것 같습니다.
이게 맞는지 아니면 제가 시각화하는 과정에서 실수를 한 건지 모르겠습니다.

2. 첫 번째 질문에서 데이터가 대서양에 중점을 둔 것이 맞다면, (아님 말고)
notebooks/ClimateDev.ipynb에서 확인할 수 있는 climate 데이터와 사용하는 지도가 다른 것 같습니다.
그래서 climate와 sea 데이터를 같이 써야 하는지, 그렇다면 같이 쓰는 방법이 있는지 알 필요가 있을 것 같습니다.

3. 그래서 무엇을 보여줘야 하는가에 대한 질문입니다.
이렇게 gif 파일을 만들기는 했는데, 결론적으로 뭐를 보여줘야 하는지 모르겠어서요. 
일단은 함수를 하나 만들어서 남는 데이터(1438번 이후 데이터)를 써서 평가하고, 
원본 데이터와 예측 결과(batch_target과 batch_output이 될 것 같네요)의 영상을 만드는 기능을 만들려고 생각하고 있습니다.
다른 방향으로 가야 하거나 확실히 보여줘야 하는 부분이 있으면 말씀해주세요.

멋 모르고 Imagemagick을 써서 gif로 나오긴 했는데, 필요하면 mp4도 찾아보겠습니다. 근데 안 필요할 걸요?

**Comment by ks1101** [comment]
mp4도 되네요
https://user-images.githubusercontent.com/55044759/130035620-46ef5e7b-057e-4f34-b37f-be1cecc2e2be.mp4

**Comment by songhune** [comment]
1> 대서양 파일이 맞습니다. 즉 climate데이터와는 다른 데이터셋입니다(위/경도가 다르죠)
2> 따로 쓰는게 맞아 보입니다만 이건 물어볼게요
3>네, 특정 부분을 딱히 보여줄 필요는 없어 보입니다. 가장 좋은 건 랜덤 배치를 뽑아서(그때그때)해당 데이터의 위치 변경 결과를 만들면 될 것 같습니다.

그리고 시각화 샘플 코드 보내주거나 아님 브랜치에 올려주세요

**Comment by songhune** [comment]
jupyter lab과 같은 ipython에서 argparse는 먹히지 않습니다.
링크 참조
https://velog.io/@yeong95/Jupyter-notebook에서-argparse-이용하기

**Comment by ks1101** [comment]
```python
import matplotlib.pyplot as plt
import matplotlib.animation as ani

'''
    시각화 부분
    fig, axs = plt.subplots()

    frames = data[:100]
    def func(frame):
        axs.imshow(frame, origin='lower')
        return axs

    animation = ani.FuncAnimation(fig=fig, func=func, frames=frames, interval = 10)
    animation.save('sample.mp4', fps=10)
    plt.show()
'''
```
