### ISSUE TITLE
테스트와 시각화 진행 상황?

### ISSUE THREAD

**Issue by ks1101** [NESAP-STL/nesap-stl#19]
전에 말씀드린 평가 함수와 결과를 시각화하는 코드를 어찌저찌해서 만들었습니다.
그런데 약간 문제가 되는 부분과 의견을 듣고 싶은 부분이 있어서 글을 남깁니다.

1.reshape_patch, reshape_patch_back 함수 사용시 이미지가 깨지는 문제

아시다시피 코드에서는 68 * 120 크기의 이미지를 16 * 17 * 30으로 바꿔서 사용을 합니다. (reshape_patch)
그렇다고 17 * 30 사이즈로 시각화하면 어딘지 모를게 뻔해서 다시 68 * 120 크기로 변환을 하려고 했습니다.
그래서 찾은 함수가 utils/preprocess.py에 있는 reshape_patch_back 함수입니다.
이름부터가 reshape_patch 한 거를 돌려주게 생겼고 실제로도 그런 기능을 합니다. 
(reshape_patch 때처럼 데이터 형식을 맞춰야해서 크기를 조절해야하는 번거로움이 있긴 합니다.)

어쨌든 reshape_patch_back 함수를 사용해서 68 * 120 크기로 만들어서 시각화를 했는데...
이미지가 깨지고 데이터 원본을 시각화한 영상보다 부드럽지 못합니다.(영상 쪽을 잘 몰라서 적절한 용어를 모르겠네요)
둘 다 68 * 120 사이즈이고, 하나는 reshape_patch 전 시점의 데이터, 다른 하나는 reshape_patch 후 reshape_patch_back을 한 데이터입니다.

https://user-images.githubusercontent.com/55044759/131466548-74174fea-942a-49e2-a11b-ba63bad93885.mp4

https://user-images.githubusercontent.com/55044759/131466562-54b13f67-dd99-49a2-9ac7-7115ccb6f295.mp4

정말 보기 안 좋네요...

그리고 70 * 125 크기의 원본이랑 비교했을 때 그리스 부분이 잘리는게 많이 티나는 것 같습니다...

https://user-images.githubusercontent.com/55044759/131467337-1488ea8f-b399-4419-9753-a1ae2a322877.mp4

2.평가에 대하여

테스트랑 시각화를 하는 코드를 만들긴 했는데 이 방식이 맞는지 모르겠네요.
그래서 테스트, 시각화를 어떤 방식으로 하면 좋을까에 대해 의견을 구하고 싶습니다.

지금 구조, 순서는 다음과 같습니다.
```
1. train.py에서 visualize.py/visual을 호출
2. visualize.py/visual에서 base.py/evaluation을 호출
3. test 데이터로 evaluation 수행
	3-1 auto_regressive.py와 같은 코드 사용
	3-2 i==10까지만 돌림 (총 10*4개의 test가 나옵니다.)
	3-3 batch_target, batch_output들을 반환
4. batch_target, batch_output 시각화 
```
이러면서 for문 등에 상수를 사용한 경우가 많은데 보기가 싫어서요.
혹시 테스트 결과가 얼마나 있는 게 좋을 것 같으신가요?
아니면 방식을 바꿀 필요가 있을까요?
아니면 다른 결과를 보여줄 수도 있을까요?

![화면 캡처 2021-08-31 170915](https://user-images.githubusercontent.com/55044759/131466736-0a1e339f-f6b1-4315-9d6d-8bdf360bc2be.png)

너무 많아요...

**Comment by songhune** [comment]
오늘 미팅을 했고. 복귀하면 이야기 나누도록 해요.
감사합니다.
